development:
  adapter: sqlite3
  host:
  encoding:
  database: ":memory:"
  pool: 5
  username:
  password:
test:
  adapter: sqlite3
  host:
  encoding:
  database: ":memory:"
  pool: 5
  username:
  password:
production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: <%=ENV['OPENSHIFT_APP_NAME']%>
  username: <%=ENV['OPENSHIFT_POSTGRESQL_DB_USERNAME']%>
  password: <%=ENV['OPENSHIFT_POSTGRESQL_DB_PASSWORD']%>
  socket: <%=ENV['OPENSHIFT_POSTGRESQL_DB_SOCKET']%>
  host: <%=ENV['OPENSHIFT_POSTGRESQL_DB_HOST']%>
  port: <%=ENV['OPENSHIFT_POSTGRESQL_DB_PORT']%>
